CREATE TABLE GAB_3637_SFDC_EPC(
ID IDENTITY DEFAULT '0',
JOB CHAR(6),
SUFFIX CHAR(3),
SEQ CHAR(6),
DATE_SEQUENCE CHAR(6),
EMPL CHAR(5),
EMPLOYEE CHAR(30),
PATCH NUMERIC (10,0),
REMOLDED NUMERIC (10,0),
NOTES LONGVARCHAR,
SEQUENCE_KEY CHAR(4),
PRIMARY KEY (ID)
);

CREATE INDEX GAB_3637 USING 1 ON GAB_3637_SFDC_EPC(JOB,SUFFIX,SEQ,DATE_SEQUENCE);